version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=@X@hBI:xK18SE"IxXz9CtQ>RCDyEWg
      - MYSQL_DATABASE=test_task
      - MYSQL_USER=yii2basic
      - MYSQL_PASSWORD=lQ:z}>nwyp4.twJ6haqr{Rj^@/KQ2+
    ports:
      - '3307:3306'